### ISSUE TITLE
npm ERR! errno -4058

### ISSUE THREAD

**Issue by Nnstein** [RajKKapadia/YouTube-Quiz-Chatbot-Dialogflow#1]
Installing dependencies with `npm install --save` returns this error for me:

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\Real_\Downloads\YouTube-Quiz-Chatbot-Dialogflow-main/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Real_\Downloads\YouTube-Quiz-Chatbot-Dialogflow-main\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Real_\AppData\Local\npm-cache\_logs\2022-12-07T13_44_12_628Z-debug-0.log

this is in my VScode GitBash terminal

**Comment by RajKKapadia** [comment]
Hi, this error says that npm ERR! enoent This is related to npm not being able to find a file.
From your terminal navigate to the location where you can see the package.json file then run `npm install --save`.

This will solve the issue.

**Comment by Nnstein** [comment]
Solved!! Thanks.
